# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Role.create(Title: 'Student')
Role.create(Title: 'Coach')
Role.create(Title: 'Admin')

Level.create(LevelName: 'Teen')
Level.create(LevelName: 'Elementary')

Team.create(Name: 'Wildcats', School: 'Clayton Park Junior High', LevelID: 1)
Team.create(Name: 'Lions', School: 'Fairview Junior High', LevelID: 1)
#Team.create(Name: 'D\'uc Danville', School: 'D\'uc Danville')

Year.create(Year: 2018)
Year.create(Year: 2017)
Year.create(Year: 2016)

#Book.create(Title: 'something', Author: 'someone', Genre: 'genred', CoverImage: 'http://sdsds', Details: 'This book is about', YearID: 2, LevelID: 1)

Book.create(Title: "The Wrath and the Dawn", Author: "Renee Ahdieh", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Anya's War", Author: "Andrea Alban", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Me and Earl and the Dying Girl", Author: "Jesse Andrews", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Mosquitoland", Author: "David Arnold", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Night Gardener", Author: "Jonathan Auxier", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Red Queen", Author: "Victoria Aveyard", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Law of Loving Others", Author: "Kate Axelrod", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Hill", Author: "Karen Bass", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Nowhere Wild", Author: "Joe Beernink", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Witch Hunter", Author: "Virginia Boecker", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Away Running", Author: "Luc Bouchard and David Wright", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Scorpion Rules", Author: "Erin Bow", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "In the Time of Dragon Moon", Author: "Janet Lee Carey", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Sight Unseen", Author: "David Carroll", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Red Wolf", Author: "Jennifer Dance", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Exquisite Captive", Author: "Heather Demetrios", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Material Girls", Author: "Elaine Dimopoulos", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Salvage", Author: "Alexandrea Duncan", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Court of Fives", Author: "Kate Elliott", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Accident Season", Author: "Moira Fowley-Doyle", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Girl at Midnight", Author: "Melissa Grey", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "In the Swish", Author: "Dawn Green", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Magonia", Author: "Maria Dahvana Headley", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Fire Horse Girl", Author: "Kay Honeyman", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Girl Defective", Author: "Simmone Howell", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "What We Hide", Author: "Marthe Jocelyn", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Going Over", Author: "Beth Kephart", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Grandmaster", Author: "Davis Klass", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Art of Secrets", Author: "James Klise", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Art of Getting Stared At", Author: "Laura Langston", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Under a Painted Sky", Author: "Stacey Lee", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Fire Wish", Author: "Amber Lough", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Egg and Spoon", Author: "Gregory Maguire", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Vanishing Girls", Author: "Lauren Oliver", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Anatomy of a Misfit", Author: "Andrea Portes", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Numbers", Author: "David Poulsen", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Snow Like Ashes", Author: "Sara Raasch", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Boy in the Black Suit", Author: "Jason Reynolds", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Bodies We Wear", Author: "Jeyn Roberts", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Bone Gap", Author: "Laura Ruby", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Blackthorn Key", Author: "Kevin Sands", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Challenger Deep", Author: "Neal Shusterman", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Are You Experienced", Author: "Jordan Sonnenblick", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Walls Around Us", Author: "Nova Ren Suma", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Dogs", Author: "Allan Stratton", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "An Ember in the Ashes", Author: "Sabaa Tahir", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Trouble is a Friend of Mine", Author: "Stephanie Tromly", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Fire Colour One", Author: "Jenny Valentine", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Like Water on Stone", Author: "Dana Walrath", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Black Dove, White Raven", Author: "Elizabeth Wein", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Afterworlds", Author: "Scott Westerfeld", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Diamond Boy", Author: "Michael Williams", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Cure for Dreaming", Author: "Cat Winters", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Belzhar", Author: "Meg Wolitzer", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Museum of Intangible Things", Author: "Wendy Wunder", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)

#User.create(Name: "Laura Nelson", UserName: "lowercase", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2)

User.create(Name: "Laura Nelson", UserName: "lowercase", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2, password: "password")
User.create(Name: "Eric Pascher", UserName: "pasche", email: "W0291149@nscc.ca", TeamID: 1, RoleID: 1, password: "password")
User.create(Name: "Jason Chen", UserName: "json", email: "W0291149@nscc.ca", TeamID: 1, RoleID: 3, password: "password")
User.create(Name: "Jeremy Stone", UserName: "thejman", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 1, password: "password")
User.create(Name: "May Mohammed", UserName: "maym", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2, password: "password")


#Question.create(Question: 'sjdsj', BookID: 1, TeamID: 2, createdBy: 3, updatedBy: 3)
#Question.create(Question: "asd", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)

#1-10
Question.create(Question: "In which book is the main character's love not who he appears to be?", BookID: 1, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is a land on the verge of an uprising?", BookID: 1, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book does the main character momentarily become the "Zombie Hug Monster"?', BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is one character's walls covered with posters of male characters, primarily Hugh Jackman?", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book are two characters called the "young nihilist" by one character\'s dad?', BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book in which the main character\'s favourite movie is "Aguirre The Wrath of God"', BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which two characters drink pho laced with marijuana (supposedly).", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which a character buys a pink fuzzy hat to cover their bald head.", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a university professor like to purchase strange animal-based food products?", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which the format periodically switches into play format.", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a character break their arm while running away from getting elbowed in the face?", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which two characters create a film involving LEGO, sock-puppets, a spinning tarantula, and a message to someone who is dying.", BookID: 3, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book did two siblings travel to Sourwoods?", BookID: 5, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book did two children leave their house to go to the Windsor House?", BookID: 5, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where there are two kinds of people: Reds and Silvers", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book that has walls that look like glass, but are really made out of diamonds.", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character make a deal with the King, where she pretends to be someone else, in order to keep her family safe?", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the future queen is selected during a Queenstrial.", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character find out that she has the ability to control electricity?", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the colour that the high born people wear indicates which family they belong?", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where the main character acquires the nickname "Little Lighting Girl".', BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book is the phrase "Anyone can betray anyone" important?', BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character finds out that her favourite brother isn't dead afterall.", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where the revolutionaries use the phrase "Rise, Red as the dawn".', BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book do we learn about First Friday, and know it's about holding power over the Reds.", BookID: 6, TeamID: 2, createdBy: 1, updatedBy: 1)

#11-20
Question.create(Question: "In which book are the children of the leaders the first to die in a war?", BookID: 12, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is Artificial Intelligence (AI) real - and in charge?", BookID: 12, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book is the first rule of war "Make it personal"?', BookID: 12, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is the main character bisexual?", BookID: 12, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do AIs hold the world hostage?", BookID: 12, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character keeps lots of lists.", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character has Stargardt's disease", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book does the main character\'s family name their cabin "Splitsville"?', BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character and his friend find a tussock / floaton / floating island?", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is one of the characters named after her blood type?", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character cross the Glimmer Line to go to Perpetuum?", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character's friend calls him a human calculator.", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character's favourite activity was to ride his bike.", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a women is researching children's heart disease in order to find a cure for her daughter.", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a boy learn Spanish to impress a girl, and later finds out that she speaks Portuguese?", BookID: 14, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character is a jinni from Arjinna.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is the main character put into a metal bottle to punish her?", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where metal is a poison to the main character and her people.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a client's wish is to have the ability to be invisible, and that wish is granted, but, not the ability to become visible again.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a ghoul kill many girls in his search to find his target?", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a slace is actually the new Empress.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where you caste is based on your eye and smoke colour, and your powers.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character mixes sleeping potion with flavoured wine, in order to steal a bottle.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a character make the hills of Los Angeles burn in order to smoke out his target?", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character determines who is running the slave trade and wants to stop them.", BookID: 16, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where people use Unum like we use cell phones, and use Tabula like we use tablets and computers.", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do people use a trendchecking gun to make sure that their clothing are in trendy?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do people take P pills (Placidophilus pills) to feel better?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a buy have a funny ticc, where he flicks his eyebrows up and down really fast, just once?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book are you called an Adequat if you are not selected as a talented person in grade 7?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where seventh graders have a "Tap" ceremony, and if they have talent, they are selected to work in one of the creative industries.', BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a designer creates a Tortue line of clothing, just to see if people will actually wear clothing that hurts.", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy defaces a statue of a famous person from their community.", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a female pop star date a male pop star because it is good for publicity?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a mom tells her daughter that she should quit her job instead of accepting a demotion?", BookID: 17, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book is there a so girl?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does on of the main characters have a bad facial scar?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book do the men take multiple wives?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book do the characters think that Earth will corrupt its women?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book does the main character escape to Earth with the help of a ship captain?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book does the main character, a ship captain, and her daughter live in the gyre?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book is the main character searching for her modrie?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book is the main character illiterate?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In what book does much of the action take place in Mumbai?", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In this book, the main character is good at fixes.", BookID: 18, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character realizes that an old friend is in ALL of her pictures on her phone.", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character kiss her ex-step-brother?", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where students type out their secrets, and place them in a special box.", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do the main characters have a Hallowe'en party in an old ghost house?", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is a girl abused by her musician boyfriend?", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where one of the characters uses the cards to answer questions.", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character buy Hallowe'en costumes at a specialty shop, that really never existed?", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character sees distorted images of herself and her family and believes them to be real.", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do we learn that the mother has sent her ex-husband away because she suspected him of doing things to her girls?", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where every October, the mother makes everything as safe as possible in their home.", BookID: 20, TeamID: 2, createdBy: 1, updatedBy: 1)

#21-30
Question.create(Question: "Name the book where two groups are at war:  the Avicen and the Drakarin.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do some of the characters need to cover themselves so that humans don't notice that they have feathers.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is the main character a thief with two rules: Don't get caught, and, If you get caught, run.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book can a person travel long distances very quickly, by using Shadow dust on a threshold and crossing the In-Between?", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a group are on a quest for the legendary Firebird.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character protect her home with wards, and needs a drop of her own blood to open the door.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where a music box playing "The Magpie\'s Lullaby" is given as a gift.', BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a person become a vessel, and gets the memories of another character's past love?", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character feels guilty after killing someone that she has always hated?", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where an important treasure is in a sealed room, and it is actually just a mirror.", BookID: 21, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where we learn that "Patzer" means Beginner.', BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a boy find out that his father was a famous chess player when he was 16 years old?", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy sees his father have a break down.", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is one of the characters a swimming athlete who abuses his girlfriend?", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a father claims to have given up something important to him,  because it wasn't a good way to meet girls.", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do the students work in a pond named after the first headmaster of their school?", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where two older boys invite a younger boy and his father to join their team in a father-son tournament in New York City.", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book where a team\'s name is "Mind Cripplers".', BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a mother-daughter team joins a tournament for father-son teams.", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a team learn that family is more important than winning?", BookID: 28, TeamID: 2, createdBy: 1, updatedBy: 1)

#31-40
Question.create(Question: "Name the book where two girls switch places with a wish on a jinni.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where students get a special tattoo indicating their group and powers when they graduate.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a girl hide the tattoo on her hand with henna?", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a jinni transport into the human palace, and later finds out that she is the only jinni who can get past the wards?", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a human is the first to see the jinni's underground cavern.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a girl finds out that her mother wasn't really her mother, and that her birth mother died when she was an infant.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a girl get her training from a man she always thought was her uncle?", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where two girls later find out that they were twins separated as infants.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a war was started by a wan who killed a couple, and then blamed the other group.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where two lamps in two different cities, join the two worlds.", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do two sisters switch places?", BookID: 32, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book did a father kill his family?", BookID: 35, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book did a girl date a guy she didn't love?", BookID: 35, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book did a school nerd turn into a bad boy?", BookID: 35, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does one character say to another, that he isn't jen-yoo-wine?", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the student's assignment is to devise a hoax, and present it to the class.", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a boy drive with his father at night, with his dead uncle between them?", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a lady's nickname is based on the digits tattooed on her arm.", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a man hate Jews so much, that he hates a woman who saved his grandfather's life?", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy gets a flat tire after dropping off his date to her home.", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a boy like to work on fixing old cars with his older brother?", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where former students often drop in on a favourite teacher's classroom during class time.", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is a boy talked into helping to burn down a house, but, realizes that they meant to burn the owner also?", BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book does the main character describe his school as "average"?', BookID: 36, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which the seasons are kingdoms.", BookID: 37, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is the main character not who she thought she was?", BookID: 37, TeamID: 2, createdBy: 1, updatedBy: 1)

#41-50
Question.create(Question: "In which book does an orphan boy become an apprentice to an apothecary?", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where two boys accidentally shoot a stuffed bear with a homemade cannon.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy decodes secret messages left to him by his master.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy is slapped and called useless and sent away, and later figures out that his master did this to save him.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do two boys find a hidden workshop by figuring out a secret code?", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is a boy's master's best friend a book seller?", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where an apprentice finds the recipe for The Archangel's Fire, and makes some of it.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is a favourite pigeon named Bridget?", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the Cult of the Archangel are killing and torturihng people.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy gets out of a locked room, by putting Oil of Vitriol on the lock.", BookID: 41, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a boy find his father's prized possession, Jimi Hendrix's famous white guitar?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy goes back in time and meets his uncle for the first time.", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do two kids cut their feet at a concern, and meet some famous musicians in the medical tent?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do two of the characters rescue a third character after he climbed a tall scaffolding in a lightning storm?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where the main character's uncle died of a drug overdose.", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do a boy and his older brother have alcoholic parents who don't take care of their sons?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does the main character have very over-protective parents?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy is actually named after himself.", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book do four teenagers get high after eating brownies that they didn't know were laced with magic mushroom?", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy goes back in time to the famous Woodstock concert.", BookID: 43, TeamID: 2, createdBy: 1, updatedBy: 1)

#51-55
Question.create(Question: "Name the book, where the main character has read the book Dracula several times.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a father have his daughter hypnotized so that she will no longer wish for votes for women, or wish to go to college?", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a girl sees the world as it really is, and as such has visions showing people differently than they look.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a mother left her child and husband to work in the theater.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book is a girl compelled to say "All is Well", when things definitely are not well?', BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a boy is working to make money in order to pay for a surgeon to remove cancer from his sister.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does a girl wish for a pair of bloomers, as it would be easier to ride her bicycle?", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'In which book does a girl vomit when she hears words like "Suffrage", "Women\'s rights", "Votes for Women", "Susan B. Anthony", and "College"?', BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where several women were hypnotized to not be able to speak, decide that they do believe in Suffrage after all.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book where a girl tells a boy that she doesn't want to be with someone who thinks she's inferior to him.", BookID: 53, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does writing in a red leather journal lead to another world?", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book are five totally different students bond through trauma and Sylvia Plath?", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book in which the main character treasures a jar of "Tiptree Little Scarlet Strawberry Preserve"', BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which one character keeps a bottle of off-brand ketchup hidden in their room.", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book in which one character\'s alcoholic mom is seen as a "charming leprechaun".', BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which the main character helps birth a goat over Thanksgiving break.", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book is the main character forced into an acapella group called the Barn tones.", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "In which book does one character find a lead on their missing brother in another world?", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: 'Name the book in which a character\'s brother spends more time in the video game "Dream Wanderer" than in the real world.', BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)
Question.create(Question: "Name the book in which a character's seemingly perfect family is broken apart over a tape of adultery.", BookID: 54, TeamID: 2, createdBy: 1, updatedBy: 1)

