# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Role.create(Title: 'Student')
Role.create(Title: 'Coach')
Role.create(Title: 'Admin')

Level.create(LevelName: 'Teen')
Level.create(LevelName: 'Elementary')

Team.create(Name: 'Wildcats', School: 'Clayton Park Junior High', LevelID: 1)
Team.create(Name: 'Lions', School: 'Fairview Junior High', LevelID: 1)
#Team.create(Name: 'D\'uc Danville', School: 'D\'uc Danville')

Year.create(Year: 2018)
Year.create(Year: 2017)
Year.create(Year: 2016)

#Book.create(Title: 'something', Author: 'someone', Genre: 'genred', CoverImage: 'http://sdsds', Details: 'This book is about', YearID: 2, LevelID: 1)

Book.create(Title: "The Wrath and the Dawn", Author: "Renee Ahdieh", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Anya's War", Author: "Andrea Alban", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Me and Earl and the Dying Girl", Author: "Jesse Andrews", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Mosquitoland", Author: "David Arnold", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Night Gardener", Author: "Jonathan Auxier", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Red Queen", Author: "Victoria Aveyard", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Law of Loving Others", Author: "Kate Axelrod", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Hill", Author: "Karen Bass", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Nowhere Wild", Author: "Joe Beernink", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Witch Hunter", Author: "Virginia Boecker", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Away Running", Author: "Luc Bouchard and David Wright", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Scorpion Rules", Author: "Erin Bow", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "In the Time of Dragon Moon", Author: "Janet Lee Carey", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Sight Unseen", Author: "David Carroll", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Red Wolf", Author: "Jennifer Dance", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Exquisite Captive", Author: "Heather Demetrios", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Material Girls", Author: "Elaine Dimopoulos", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Salvage", Author: "Alexandrea Duncan", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Court of Fives", Author: "Kate Elliott", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Accident Season", Author: "Moira Fowley-Doyle", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Girl at Midnight", Author: "Melissa Grey", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "In the Swish", Author: "Dawn Green", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Magonia", Author: "Maria Dahvana Headley", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Fire Horse Girl", Author: "Kay Honeyman", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Girl Defective", Author: "Simmone Howell", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "What We Hide", Author: "Marthe Jocelyn", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Going Over", Author: "Beth Kephart", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Grandmaster", Author: "Davis Klass", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Art of Secrets", Author: "James Klise", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Art of Getting Stared At", Author: "Laura Langston", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Under a Painted Sky", Author: "Stacey Lee", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Fire Wish", Author: "Amber Lough", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Egg and Spoon", Author: "Gregory Maguire", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Vanishing Girls", Author: "Lauren Oliver", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Anatomy of a Misfit", Author: "Andrea Portes", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Numbers", Author: "David Poulsen", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Snow Like Ashes", Author: "Sara Raasch", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Boy in the Black Suit", Author: "Jason Reynolds", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Bodies We Wear", Author: "Jeyn Roberts", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Bone Gap", Author: "Laura Ruby", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Blackthorn Key", Author: "Kevin Sands", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Challenger Deep", Author: "Neal Shusterman", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Are You Experienced", Author: "Jordan Sonnenblick", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Walls Around Us", Author: "Nova Ren Suma", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Dogs", Author: "Allan Stratton", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "An Ember in the Ashes", Author: "Sabaa Tahir", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Trouble is a Friend of Mine", Author: "Stephanie Tromly", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Fire Colour One", Author: "Jenny Valentine", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Like Water on Stone", Author: "Dana Walrath", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Black Dove, White Raven", Author: "Elizabeth Wein", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Afterworlds", Author: "Scott Westerfeld", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Diamond Boy", Author: "Michael Williams", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Cure for Dreaming", Author: "Cat Winters", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "Belzhar", Author: "Meg Wolitzer", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)
Book.create(Title: "The Museum of Intangible Things", Author: "Wendy Wunder", Genre: "TEEN", CoverImage: "a", Details: "book", YearID: 2, LevelID: 1)

#User.create(Name: "Laura Nelson", UserName: "lowercase", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2)

# User.create(Name: "Laura Nelson", UserName: "lowercase", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2, password: "password")
# User.create(Name: "Eric Pascher", UserName: "pasche", email: "W0291149@nscc.ca", TeamID: 1, RoleID: 1, password: "password")
# User.create(Name: "Jason Chen", UserName: "json", email: "W0291149@nscc.ca", TeamID: 1, RoleID: 3, password: "password")
# User.create(Name: "Jeremy Stone", UserName: "thejman", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 1, password: "password")
# User.create(Name: "May Mohammed", UserName: "maym", email: "W0291149@nscc.ca", TeamID: 2, RoleID: 2, password: "password")


#Question.create(Question: 'sjdsj', BookID: 1, TeamID: 2, CreatedBy: 3, UpdatedBy: 3)

#1-10
Question.create(Question: "In which book is the main character's love not who he appears to be?", BookID: 1, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is a land on the verge of an uprising?", BookID: 1, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'In which book does the main character momentarily become the "Zombie Hug Monster"?', BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is one character's walls covered with posters of male characters, primarily Hugh Jackman?", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'In which book are two characters called the "young nihilist" by one character\'s dad?', BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'Name the book in which the main character\'s favourite movie is "Aguirre The Wrath of God"', BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book in which two characters drink pho laced with marijuana (supposedly).", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book in which a character buys a pink fuzzy hat to cover their bald head.", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a university professor like to purchase strange animal-based food products?", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book in which the format periodically switches into play format.", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a character break their arm while running away from getting elbowed in the face?", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book in which two characters create a film involving LEGO, sock-puppets, a spinning tarantula, and a message to someone who is dying.", BookID: 3, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book did two siblings travel to Sourwoods?", BookID: 5, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book did two children leave their house to go to the Windsor House?", BookID: 5, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where there are two kinds of people: Reds and Silvers", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book that has walls that look like glass, but are really made out of diamonds.", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character make a deal with the King, where she pretends to be someone else, in order to keep her family safe?", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the future queen is selected during a Queenstrial.", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character find out that she has the ability to control electricity?", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the colour that the high born people wear indicates which family they belong?", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'Name the book where the main character acquires the nickname "Little Lighting Girl".', BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'In which book is the phrase "Anyone can betray anyone" important?', BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character finds out that her favourite brother isn't dead afterall.", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'Name the book where the revolutionaries use the phrase "Rise, Red as the dawn".', BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book do we learn about First Friday, and know it's about holding power over the Reds.", BookID: 6, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)


#11-20
Question.create(Question: "In which book are the children of the leaders the first to die in a war?", BookID: 12, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is Artificial Intelligence (AI) real - and in charge?", BookID: 12, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'In which book is the first rule of war "Make it personal"?', BookID: 12, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is the main character bisexual?", BookID: 12, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book do AIs hold the world hostage?", BookID: 12, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character keeps lots of lists.", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character has Stargardt's disease", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'In which book does the main character\'s family name their cabin "Splitsville"?', BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character and his friend find a tussock / floaton / floating island?", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is one of the characters named after her blood type?", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character cross the Glimmer Line to go to Perpetuum?", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character's friend calls him a human calculator.", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character's favourite activity was to ride his bike.", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a women is researching children's heart disease in order to find a cure for her daughter.", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a boy learn Spanish to impress a girl, and later finds out that she speaks Portuguese?", BookID: 14, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character is a jinni from Arjinna.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is the main character put into a metal bottle to punish her?", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where metal is a poison to the main character and her people.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a client's wish is to have the ability to be invisible, and that wish is granted, but, not the ability to become visible again.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a ghoul kill many girls in his search to find his target?", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a slace is actually the new Empress.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where you caste is based on your eye and smoke colour, and your powers.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character mixes sleeping potion with flavoured wine, in order to steal a bottle.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a character make the hills of Los Angeles burn in order to smoke out his target?", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character determines who is running the slave trade and wants to stop them.", BookID: 16, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where people use Unum like we use cell phones, and use Tabula like we use tablets and computers.", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book do people use a trendchecking gun to make sure that their clothing are in trendy?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book do people take P pills (Placidophilus pills) to feel better?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a buy have a funny ticc, where he flicks his eyebrows up and down really fast, just once?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book are you called an Adequat if you are not selected as a talented person in grade 7?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: 'Name the book where seventh graders have a "Tap" ceremony, and if they have talent, they are selected to work in one of the creative industries.', BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a designer creates a Tortue line of clothing, just to see if people will actually wear clothing that hurts.", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a boy defaces a statue of a famous person from their community.", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does a female pop star date a male pop star because it is good for publicity?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where a mom tells her daughter that she should quit her job instead of accepting a demotion?", BookID: 17, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book is there a so girl?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does on of the main characters have a bad facial scar?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book do the men take multiple wives?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book do the characters think that Earth will corrupt its women?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book does the main character escape to Earth with the help of a ship captain?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book does the main character, a ship captain, and her daughter live in the gyre?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book is the main character searching for her modrie?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book is the main character illiterate?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In what book does much of the action take place in Mumbai?", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In this book, the main character is good at fixes.", BookID: 18, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character realizes that an old friend is in ALL of her pictures on her phone.", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character kiss her ex-step-brother?", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where students type out their secrets, and place them in a special box.", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book do the main characters have a Hallowe'en party in an old ghost house?", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book is a girl abused by her musician boyfriend?", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where one of the characters uses the cards to answer questions.", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book does the main character buy Hallowe'en costumes at a specialty shop, that really never existed?", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where the main character sees distorted images of herself and her family and believes them to be real.", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "In which book do we learn that the mother has sent her ex-husband away because she suspected him of doing things to her girls?", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
Question.create(Question: "Name the book where every October, the mother makes everything as safe as possible in their home.", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)

#21-30

#Question.create(Question: "asd", BookID: 20, TeamID: 2, CreatedBy: 1, UpdatedBy: 1)
